name: Deploy Nest API to Azure App Service (OIDC)

on:
  push:
    branches: [ main ]
    paths:
      - "**/*.ts"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/deploy-api.yml"

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: "20"
  APP_NAME: "azure-pet-demo-back"     

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare artifact
        run: |
          mkdir -p out
          cp -r dist package.json package-lock.json out/
          cd out && zip -r app.zip .

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          package: out/app.zip
